/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-01-30 05:37:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"refresh\" content=\"2.6 ;URL='HomeAction'\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Inconsolata|Playfair+Display|Rubik\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"A simple library to take care of complex CSS animations.\" />\r\n");
      out.write("<canvas id=\"animation\"></canvas>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    /* CSSアニメーションの設定 */\r\n");
      out.write("    .scroll-overlay {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tz-index: 99;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("html {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tmargin: 0 0;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("overflow: hidden;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\t/* width: 1920px; */\r\n");
      out.write("\tmargin: 0 0;\r\n");
      out.write("\tbackground-color: #FFFAFA;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("}\r\n");
      out.write("::-webkit-scrollbar {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("       .poyon {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.4s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write(".poyon1 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.2s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon2 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.3s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon3 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.7s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon4 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.6s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon5 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.4s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon6 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.7s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon7 {\r\n");
      out.write("      -webkit-animation: poyon 2.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 2.1s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon8 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.4s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon9 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.2s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon10 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.6s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("     .poyon11 {\r\n");
      out.write("      -webkit-animation: poyon 1.1s linear 0s 1;\r\n");
      out.write("      animation: poyon 1.7s linear 0s 1;\r\n");
      out.write("    }\r\n");
      out.write("   .anime{\r\n");
      out.write("   \ttext-align: center;\r\n");
      out.write("   \tmargin: 0 auto;\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:300px;\r\n");
      out.write("\tleft:300px;\r\n");
      out.write("   }\r\n");
      out.write("   .description {\r\n");
      out.write("   position:absolute;\r\n");
      out.write("\ttop:500px;\r\n");
      out.write("\tleft:590px;\r\n");
      out.write("\t\tfont-size:30px;\r\n");
      out.write("\t\tletter-spacing:5px;\r\n");
      out.write("\t\tanimation: fadeIn 3s ease 0s 1 normal;\r\n");
      out.write("    -webkit-animation: fadeIn 3s ease 0s 1 normal;\r\n");
      out.write("\t}\r\n");
      out.write("\t@keyframes fadeIn {\r\n");
      out.write("    0% {opacity: 0}\r\n");
      out.write("    20% {opacity:0}\r\n");
      out.write("    100% {opacity: 1}\r\n");
      out.write("}\r\n");
      out.write("    @-webkit-keyframes poyon {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("  @-webkit-keyframes poyon2 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon2 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon3 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon3 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon4 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon4 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon5 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon5 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon6 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon6 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon7 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      300%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -80%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon7 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon8 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon8 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon9 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon9 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon10 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon10 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("      @-webkit-keyframes poyon11 {\r\n");
      out.write("      0%   { -webkit-transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { -webkit-transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { -webkit-transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { -webkit-transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { -webkit-transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { -webkit-transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { -webkit-transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes poyon11 {\r\n");
      out.write("      0%   { transform: scale(0.8, 1.4) translate(0%, -100%); }\r\n");
      out.write("      10%  { transform: scale(0.8, 1.4) translate(0%, -60%); }\r\n");
      out.write("      20%  { transform: scale(1.4, 0.6) translate(0%, 30%); }\r\n");
      out.write("      30%  { transform: scale(0.9, 1.1) translate(0%, -10%); }\r\n");
      out.write("      40%  { transform: scale(0.95, 1.2) translate(0%, -30%); }\r\n");
      out.write("      200%  { transform: scale(0.95, 1.2) translate(0%, -10%); }\r\n");
      out.write("      60%  { transform: scale(1.1, 0.9) translate(0%, 5%); }\r\n");
      out.write("      70%  { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("      100% { transform: scale(1.0, 1.0) translate(0%, 0%); }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script src=\"js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t\t<div id=\"header\" class=\"header\">\r\n");
      out.write("\t\t\t<canvas id=\"animation\"></canvas>\r\n");
      out.write("\t\t\t<h1></h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"anime\">\r\n");
      out.write("  <img id=\"logo\" class=\"poyon\" src=\"./logo/01_l.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("   <img id=\"logo1\" class=\"poyon1\" src=\"logo/02_e.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("    <img id=\"logo2\" class=\"poyon2\" src=\"logo/03_i.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("     <img id=\"logo3\" class=\"poyon3\" src=\"logo/04_s.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("      <img id=\"logo4\" class=\"poyon4\" src=\"logo/05_u.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("       <img id=\"logo5\" class=\"poyon5\" src=\"logo/06_r.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("        <img id=\"logo6\" class=\"poyon6\" src=\"logo/07_e.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("         <img id=\"logo7\" class=\"poyon7\" src=\"logo/08_p.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("          <img id=\"logo8\" class=\"poyon8\" src=\"logo/09_a.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("           <img id=\"logo9\" class=\"poyon9\" src=\"logo/10_s.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("            <img id=\"logo10\" class=\"poyon10\" src=\"logo/11_s.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("             <img id=\"logo11\" class=\"poyon11\" src=\"logo/12_!.jpg\" width=\"auto\" height=\"200\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <p class=\"description\">Let's Enjoy Japan!!</p>\r\n");
      out.write("  \t<div class=\"scroll-overlay\"></div>\r\n");
      out.write("  <script>\r\n");
      out.write("    // ID値「mitarashi」に対してCSSアニメ―ション「poyon」を300ミリ秒の間隔を空けてループ再生\r\n");
      out.write("    looopAnimation(\"logo\", \"poyon\", 300);\r\n");
      out.write("    looopAnimation(\"logo1\", \"poyon1\", 300);\r\n");
      out.write("    looopAnimation(\"logo2\", \"poyon2\", 300);\r\n");
      out.write("    looopAnimation(\"logo3\", \"poyon3\", 300);\r\n");
      out.write("    looopAnimation(\"logo4\", \"poyon4\", 300);\r\n");
      out.write("    looopAnimation(\"logo5\", \"poyon5\", 300);\r\n");
      out.write("    looopAnimation(\"logo6\", \"poyon6\", 300);\r\n");
      out.write("    looopAnimation(\"logo7\", \"poyon7\", 300);\r\n");
      out.write("    looopAnimation(\"logo8\", \"poyon8\", 300);\r\n");
      out.write("    looopAnimation(\"logo9\", \"poyon9\", 300);\r\n");
      out.write("    looopAnimation(\"logo10\", \"poyon10\", 300);\r\n");
      out.write("    looopAnimation(\"logo11\", \"poyon11\", 300);\r\n");
      out.write("  </script>\r\n");
      out.write("  \t<script src=\"./js/animu.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
